### PR TITLE
Add PseudoObservationsFITC

### PR DESCRIPTION
**Pull request by patel-zeel**
Added main class and tests for [FITC sparse regression](http://www.gatsby.ucl.ac.uk/~snelson/SPGP_up.pdf).

### CODE REVIEW

**Comment by patel-zeel** [comment]
Hi @wesselb,

Sorry for returning to this after a long time. 

I have made the following changes:
* Removed SparseObs and backward compatibility code for it.
* Using ```PseudoObservations``` as a parent class for ```PseudoObsVFE``` and ```PseudoObsFITC```.
* Using a single ```@pytest.mark.parametrize``` for ```PseudoObsVFE``` and ```PseudoObsFITC```.
* Corrected ```example*.py``` and README to incorporate change from  ```PseudoObsVFE``` to ```PseudoObs```

Please let me know wherever minor/major changes are required.

**Comment by wesselb** [comment]
Hey @patel-zeel, absolutely no rush! This is looking great now. :)

Only one comment really: it might not be a good idea to rename `PseudoObs` to `PseudoObsVFE`, since that would break existing code depending on the name `PseudoObs`. I therefore suggest the following renaming:

* `PseudoObservations` -> `AbstractPseudoObservations` (to avoid a clash with naming `PseudoObservationsVFE` back to `PseudoObservations`)
* `PseudoObservationsVFE` -> `PseudoObservations`

With those changed, this seems ready to go! I really appreciate the contribution. :)

**Comment by patel-zeel** [comment]
Hey @wesselb,

Your suggestion makes perfect sense. I have applied it to the relevant places.

Thank you for your iterative suggestions on this PR. It has been a really good learning experience for me :)

**Comment by wesselb** [comment]
Thank you @patel-zeel! And no problem at all. :)

This is really great! Your contribution is really appreciated. Super happy to have another approximation implemented.

I've merged the PR. I will release another version of the package in the next few days which includes the FITC approximation.  :)

**Comment by patel-zeel** [comment]
Sounds great! Thank you @wesselb :)

**Pull request merged**
